### ISSUE TITLE
🔭Roadmap

### ISSUE THREAD

**Issue by igorbenav** [igorbenav/FastAPI-boilerplate#38]
## 🔭To Do
Not exactly a roadmap, more of a possible TODO kind of list:

### ⚡️API
- [ ] Add a photo upload endpoint for users
- [ ] Add possibility of comments in posts
- [ ] Add webhook to notify when a new comment is added in post
- [ ] Expire jwt token (blacklist)

### 📝Docs
- [ ] Docs for other databases (MysQL, SQLite)
- [ ] warn to make sure DB and tables are created before running create_superuser and create_tier scripts
- [ ] remind to pass "api/v1/..." in the path for rate_limiter

### 🚀Features
- [x] Add a Rate Limiter dependency #37 
- [ ] Add mongoDB support
- [ ] get_joined in CRUD

### 🧪Tests
- [ ] Add Ruff linter
